/**
 * Created by a.milko on 03.03.2016.
 */
export const PUSH_COUNTRY = 'PUSH_COUNTRY';
export const SUCCESS_RESPONSE_COUNTRY = 'SUCCESS_RESPONSE_COUNTRY';
export const FAIL_RESPONSE_COUNTRY = 'FAIL_RESPONSE_COUNTRY';
export const SET_LOADING_VISIBLE_COUNTRY = 'SET_LOADING_VISIBLE_COUNTRY';

